=== ALSETLab/cim2modelica/res/cim_iteslalibrary_gensal.dtd
<!ELEMENT GENSALMap (mapAttribute+)>
<!ATTLIST GENSALMap
          GeneratingUnit CDATA #REQUIRED
          SynchronousMachineDynamics CDATA #REQUIRED
          cim_name CDATA #REQUIRED
          name CDATA #REQUIRED
          package CDATA #REQUIRED
          rfd_id CDATA #REQUIRED
          stereotype CDATA #REQUIRED>
<!ELEMENT mapAttribute (#PCDATA)>
<!ATTLIST mapAttribute
          cim_name CDATA #REQUIRED
          datatype CDATA #REQUIRED
          mo_name CDATA #REQUIRED
          variability CDATA #REQUIRED
          visibility CDATA #REQUIRED>

=== ALSETLab/cim2modelica/res/map/cim_iteslalibrary_gensal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "cim_iteslalibrary_gensal.dtd">
<GENSALMap cim_name="SynchronousMachine" rfd_id="" package="iPSL.Electrical.Machines.PSSE.GENSAL" name="GENSAL" stereotype="class">
  <mapAttribute cim_name="GeneratingUnit.baseP" mo_name="S_b" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachine.ratedS" mo_name="M_b" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachine.ratedU" mo_name="V_b" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="IdentifiedObject.name" mo_name="InstanceName" datatype="String" variability="none" visibility="none">GENSAL</mapAttribute>
  <mapAttribute cim_name="SvVoltage.v" mo_name="V_0" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SvVoltage.angle" mo_name="angle_0" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachine.p" mo_name="P_0" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachine.q" mo_name="Q_0" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachineDynamics.statorResistance" mo_name="R_a" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachineDynamics.statorLeakageReactance" mo_name="Xl" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachineDynamics.inertia" mo_name="H" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachineDynamics.damping" mo_name="D" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachineDynamics.saturationFactor" mo_name="S10" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachineDynamics.saturationFactor120" mo_name="S12" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.tpdo" mo_name="Tpd0" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.tppdo" mo_name="Tppd0" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.tppqo" mo_name="Tppq0" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.xDirectSync" mo_name="Xd" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.xDirectTrans" mo_name="Xpd" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.xDirectSubtrans" mo_name="Xppd" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.xQuadSync" mo_name="Xq" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.xQuadSubtrans" mo_name="Xppq" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
</GENSALMap>

=== ALSETLab/cim2modelica/res/cim_iteslalibrary_gensal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "cim_iteslalibrary_gensal.dtd">
<GENSALMap cim_name="SynchronousMachine" rfd_id="" package="PowerSystems.Electrical.Machines.PSSE" name="GENSAL" stereotype="class"
  GeneratingUnit="GeneratingUnit" SynchronousMachineDynamics="SynchronousMachineTimeConstantReactance">
  <mapAttribute cim_name="IdentifiedObject.name" mo_name="InstanceName" datatype="String" variability="none" visibility="none">gencls</mapAttribute>
  <mapAttribute cim_name="SvVoltage.v" mo_name="eterm" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SvVoltage.angle" mo_name="anglev0" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SvPowerFlow.p" mo_name="pelec" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SvPowerFlow.q" mo_name="qelec" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="GeneratingUnit.nominalP" mo_name="Mbase" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="BasePower.basePower" mo_name="Sbase" datatype="Real" variability="parameter" visibility="public"></mapAttribute> 
  <mapAttribute cim_name="RotatingMachine.statorResistance" mo_name="ra" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.tpdo" mo_name="Tpd0" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.tppdo" mo_name="Tppd0" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.tppqo" mo_name="Tppq0" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachine.inertia" mo_name="H" datatype="Real" variability="parameter" visibility="public"></mapAttribute>  
  <mapAttribute cim_name="RotatingMachine.damping" mo_name="D" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.xDirectSync" mo_name="Xd" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.xQuadSync" mo_name="Xq" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.xDirectTrans" mo_name="Xpd" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.xDirectSubtrans" mo_name="Xppd" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachineTimeConstantReactance.xQuadSubtrans" mo_name="Xppq" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="SynchronousMachine.x" mo_name="Xl" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachine.saturationFactor" mo_name="s10" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
  <mapAttribute cim_name="RotatingMachine.saturationFactor120" mo_name="s12" datatype="Real" variability="parameter" visibility="public"></mapAttribute>
</GENSALMap>
