=== ALSETLab/cim2modelica/res/map/cimcomposer/cim_ipsl_pwline.dtd
<!ELEMENT pwLineMap (mapAttribute+)>
<!ATTLIST pwLineMap
		  cim_name CDATA #REQUIRED
		  cim_mRID CDATA #REQUIRED
          mo_name CDATA #REQUIRED
          mo_package CDATA #REQUIRED
          mo_stereotype CDATA #REQUIRED>
<!ELEMENT attributeMap (#PCDATA)>
<!ATTLIST attributeMap
          cim_name CDATA #REQUIRED
          datatype CDATA #REQUIRED
          mo_name CDATA #REQUIRED
          variability CDATA #REQUIRED
          visibility CDATA #REQUIRED>

=== ALSETLab/cim2modelica/res/map/cimcomposer/cim_ipsl_pwline.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--Created by fragom-->
<!DOCTYPE model SYSTEM "cim_ipsl_pwline.dtd">
<pwLineMap cim_name="ACLineSegment" cim_mRID="" mo_name="ACLineSegment" package="iPSL.Electrical.Branches" stereotype="class">
  <attributeMap cim_name="IdentifiedObject.name" mo_name="InstanceName" datatype="String" variability="none" visibility="none">name</attributeMap>
  <attributeMap cim_name="IdentifiedObject.mRID" mo_name="InstanceName" datatype="String" variability="none" visibility="none">mRID</attributeMap>
  <attributeMap cim_name="ACLineSegment.r" mo_name="R" datatype="Real" variability="parameter" visibility="public">0</attributeMap>
  <attributeMap cim_name="ACLineSegment.x" mo_name="X" datatype="Real" variability="parameter" visibility="public">0</attributeMap>
  <attributeMap cim_name="ACLineSegment.gch" mo_name="G" datatype="Real" variability="parameter" visibility="public">0</attributeMap>
  <attributeMap cim_name="ACLineSegment.bch" mo_name="B" datatype="Real" variability="parameter" visibility="public">0</attributeMap>
  <attributeMap cim_name="none" mo_name="t1" datatype="Real" variability="parameter" visibility="public">Modelica.Constants.inf</attributeMap>
  <attributeMap cim_name="none" mo_name="t2" datatype="Real" variability="parameter" visibility="public">Modelica.Constants.inf</attributeMap>
  <attributeMap cim_name="none" mo_name="opening" datatype="String" variability="none" visibility="none">1</attributeMap>
  <attributeMap cim_name="none" mo_name="displayPF" datatype="String" variability="none" visibility="none">true</attributeMap>
</pwLineMap>
