=== ALSETLab/cim2modelica/res/map/general/cim_modelica_terminal.dtd
<!ELEMENT terminalMap (svPowerFlowMap, topologicalNodeMap, conductingEquipmentMap)>
<!ATTLIST terminalMap
          cim_mRID CDATA #REQUIRED
          cim_name CDATA #REQUIRED
          mo_package CDATA #REQUIRED
          mo_stereotype CDATA #REQUIRED
          rfd_id CDATA #REQUIRED>
<!ELEMENT svPowerFlowMap (modelVariableMap+)>
<!ATTLIST svPowerFlowMap
          cim_mRID CDATA #REQUIRED
          cim_name CDATA #REQUIRED
          rfd_id CDATA #REQUIRED>
<!ELEMENT modelVariableMap (#PCDATA)>
<!ATTLIST modelVariableMap
          cim_name CDATA #REQUIRED
          mo_datatype CDATA #REQUIRED
          mo_variability CDATA #REQUIRED
          mo_visibility CDATA #REQUIRED>
<!ELEMENT topologicalNodeMap (svVoltageMap)>
<!ATTLIST topologicalNodeMap
          cim_mRID CDATA #REQUIRED
          cim_name CDATA #REQUIRED
          rfd_id CDATA #REQUIRED>
<!ELEMENT svVoltageMap (modelVariableMap+)>
<!ATTLIST svVoltageMap
          cim_mRID CDATA #REQUIRED
          cim_name CDATA #REQUIRED
          rfd_id CDATA #REQUIRED>
<!ELEMENT conductingEquipmentMap (#PCDATA)>
<!ATTLIST conductingEquipmentMap
          cim_mRID CDATA #REQUIRED
          cim_name CDATA #REQUIRED
          rfd_id CDATA #REQUIRED>

=== ALSETLab/cim2modelica/res/map/general/cim_modelica_terminal.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--Created by fragom-->
<!DOCTYPE model SYSTEM "cim_modelica_terminal.dtd">
<terminalMap cim_name="IdentifiedObject.name" cim_mRID="IdentifiedObject.mRID" mo_package="Connectors" mo_stereotype="connector">
	<svPowerFlowMap cim_name="IdentifiedObject.name" cim_mRID="IdentifiedObject.mRID">
 		<modelVariableMap cim_name="SvPowerFlow.p" mo_datatype="Real" mo_variability="variable" mo_visibility="public">-1</modelVariableMap>
 		<modelVariableMap cim_name="SvPowerFlow.q" mo_datatype="Real" mo_variability="variable" mo_visibility="public">-1</modelVariableMap>
	</svPowerFlowMap>
	<topologicalNodeMap cim_name="IdentifiedObject.name" cim_mRID="IdentifiedObject.mRID">
		<svVoltageMap cim_name="IdentifiedObject.name" cim_mRID="IdentifiedObject.mRID">
			<modelVariableMap cim_name="SvVoltage.v" mo_datatype="Real" mo_variability="variable" mo_visibility="public">-1</modelVariableMap>
			<modelVariableMap cim_name="SvVoltage.angle" mo_datatype="Real" mo_variability="variable" mo_visibility="public">-1</modelVariableMap>
		</svVoltageMap>
	</topologicalNodeMap>
</terminalMap>
